export type TabType =
  | "chat"
  | "skills"
  | "marketplace"
  | "assistants"
  | "users"
  | "roles"
  | "settings"
  | "mcp"
  | "feedback"
  | "channels"
  | "agents"
  | "models"
  | "files"
  | "notifications"
  | "memory"
  | "assistant-detail";
