"""Setting metadata definitions - Memory domain (split from _definitions_extra)."""

from __future__ import annotations

from src.kernel.schemas.setting import SettingCategory, SettingType

MEMORY_SETTING_DEFINITIONS: dict[str, dict] = {
    "NATIVE_MEMORY_INDEX_ENABLED": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "index",
        "description": "settingDesc.NATIVE_MEMORY_INDEX_ENABLED",
        "default": True,
        "depends_on": "ENABLE_MEMORY",
        "frontend_visible": True,
    },
    "NATIVE_MEMORY_QUERY_CONTEXT_ENABLED": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "query_context",
        "description": "settingDesc.NATIVE_MEMORY_QUERY_CONTEXT_ENABLED",
        "default": False,
        "depends_on": "ENABLE_MEMORY",
        "frontend_visible": True,
    },
    "NATIVE_MEMORY_QUERY_CONTEXT_TOP_K": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "query_context",
        "description": "settingDesc.NATIVE_MEMORY_QUERY_CONTEXT_TOP_K",
        "default": 3,
        "depends_on": "ENABLE_MEMORY",
        "frontend_visible": True,
    },
    "NATIVE_MEMORY_QUERY_CONTEXT_MAX_CHARS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "query_context",
        "description": "settingDesc.NATIVE_MEMORY_QUERY_CONTEXT_MAX_CHARS",
        "default": 1200,
        "depends_on": "ENABLE_MEMORY",
        "frontend_visible": True,
    },
    "NATIVE_MEMORY_SELF_EVOLVE_ENABLED": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "self_evolve",
        "description": "settingDesc.NATIVE_MEMORY_SELF_EVOLVE_ENABLED",
        "default": False,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_SELF_EVOLVE_MAX_PER_NIGHT": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "self_evolve",
        "description": "settingDesc.NATIVE_MEMORY_SELF_EVOLVE_MAX_PER_NIGHT",
        "default": 3,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_SELF_EVOLVE_INTERVAL_SECONDS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "self_evolve",
        "description": "settingDesc.NATIVE_MEMORY_SELF_EVOLVE_INTERVAL_SECONDS",
        "default": 43200,
        "depends_on": "ENABLE_MEMORY",
    },
    "MEMORY_EXTRACTION_ENABLED": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "extraction",
        "description": "settingDesc.MEMORY_EXTRACTION_ENABLED",
        "default": True,
        "depends_on": "ENABLE_MEMORY",
    },
    "MEMORY_EXTRACTION_IDLE_SECONDS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "extraction",
        "description": "settingDesc.MEMORY_EXTRACTION_IDLE_SECONDS",
        "default": 1800,
        "depends_on": "ENABLE_MEMORY",
    },
    "MEMORY_EXTRACTION_MAX_AGE_DAYS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "extraction",
        "description": "settingDesc.MEMORY_EXTRACTION_MAX_AGE_DAYS",
        "default": 30,
        "depends_on": "ENABLE_MEMORY",
    },
    "MEMORY_EXTRACTION_MAX_SESSIONS_PER_PASS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "extraction",
        "description": "settingDesc.MEMORY_EXTRACTION_MAX_SESSIONS_PER_PASS",
        "default": 3,
        "depends_on": "ENABLE_MEMORY",
    },
    "MEMORY_EXTRACTION_MAX_ATTEMPTS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "extraction",
        "description": "settingDesc.MEMORY_EXTRACTION_MAX_ATTEMPTS",
        "default": 3,
        "depends_on": "ENABLE_MEMORY",
    },
    "MEMORY_EXTRACTION_TRANSCRIPT_MAX_CHARS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "extraction",
        "description": "settingDesc.MEMORY_EXTRACTION_TRANSCRIPT_MAX_CHARS",
        "default": 24000,
        "depends_on": "ENABLE_MEMORY",
    },
    "MEMORY_EXTRACTION_INTERVAL_SECONDS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "extraction",
        "description": "settingDesc.MEMORY_EXTRACTION_INTERVAL_SECONDS",
        "default": 900,
        "depends_on": "ENABLE_MEMORY",
    },
    "SYSTEMONE_API_BASE": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "extraction",
        "description": "settingDesc.SYSTEMONE_API_BASE",
        "default": "",
        "depends_on": "ENABLE_MEMORY",
    },
    "SYSTEMONE_API_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "extraction",
        "description": "settingDesc.SYSTEMONE_API_KEY",
        "default": "",
        "is_sensitive": True,
        "depends_on": "ENABLE_MEMORY",
    },
    "SYSTEMONE_MODEL": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "extraction",
        "description": "settingDesc.SYSTEMONE_MODEL",
        "default": "jev-latest",
        "depends_on": "ENABLE_MEMORY",
    },
    "SYSTEMONE_TIMEOUT_SECONDS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "extraction",
        "description": "settingDesc.SYSTEMONE_TIMEOUT_SECONDS",
        "default": 5.0,
        "depends_on": "ENABLE_MEMORY",
    },
    "MEMORY_EXTRACTION_SYSTEMONE_MODE": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "extraction",
        "description": "settingDesc.MEMORY_EXTRACTION_SYSTEMONE_MODE",
        "default": "off",
        "depends_on": "ENABLE_MEMORY",
    },
    "MEMORY_EXTRACTION_SYSTEMONE_GATE_THRESHOLD": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "extraction",
        "description": "settingDesc.MEMORY_EXTRACTION_SYSTEMONE_GATE_THRESHOLD",
        "default": 0.35,
        "depends_on": "ENABLE_MEMORY",
    },
    "MEMORY_EXTRACTION_SYSTEMONE_CONTEXT_SHADOW": {
        "type": SettingType.BOOLEAN,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "extraction",
        "description": "settingDesc.MEMORY_EXTRACTION_SYSTEMONE_CONTEXT_SHADOW",
        "default": False,
        "depends_on": "ENABLE_MEMORY",
    },
    "MEMORY_DEDUP_SYSTEMONE_MODE": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "dedup",
        "description": "settingDesc.MEMORY_DEDUP_SYSTEMONE_MODE",
        "default": "off",
        "depends_on": "ENABLE_MEMORY",
    },
    "MEMORY_DEDUP_SYSTEMONE_GRAY_LOW": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "dedup",
        "description": "settingDesc.MEMORY_DEDUP_SYSTEMONE_GRAY_LOW",
        "default": 0.75,
        "depends_on": "ENABLE_MEMORY",
    },
    "MEMORY_DEDUP_SYSTEMONE_GRAY_HIGH": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "dedup",
        "description": "settingDesc.MEMORY_DEDUP_SYSTEMONE_GRAY_HIGH",
        "default": 0.92,
        "depends_on": "ENABLE_MEMORY",
    },
    "MEMORY_DEDUP_SYSTEMONE_SAME_THRESHOLD": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "dedup",
        "description": "settingDesc.MEMORY_DEDUP_SYSTEMONE_SAME_THRESHOLD",
        "default": 0.8,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_VECTOR_BACKEND": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "vector",
        "description": "settingDesc.NATIVE_MEMORY_VECTOR_BACKEND",
        "default": "mongo",
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_QDRANT_URL": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "vector",
        "description": "settingDesc.NATIVE_MEMORY_QDRANT_URL",
        "default": "http://127.0.0.1:6333",
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_QDRANT_API_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "vector",
        "description": "settingDesc.NATIVE_MEMORY_QDRANT_API_KEY",
        "default": "",
        "is_sensitive": True,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_INDEX_CACHE_TTL": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "index",
        "description": "settingDesc.NATIVE_MEMORY_INDEX_CACHE_TTL",
        "default": 300,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_RERANK_MODEL": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "rerank",
        "description": "settingDesc.NATIVE_MEMORY_RERANK_MODEL",
        "default": "",
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_RERANK_API_BASE": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "rerank",
        "description": "settingDesc.NATIVE_MEMORY_RERANK_API_BASE",
        "default": "",
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_RERANK_API_KEY": {
        "type": SettingType.STRING,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "rerank",
        "description": "settingDesc.NATIVE_MEMORY_RERANK_API_KEY",
        "default": "",
        "is_sensitive": True,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_MAX_TOKENS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "limits",
        "description": "settingDesc.NATIVE_MEMORY_MAX_TOKENS",
        "default": 0,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_INLINE_CONTENT_MAX_CHARS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "limits",
        "description": "settingDesc.NATIVE_MEMORY_INLINE_CONTENT_MAX_CHARS",
        "default": 1200,
        "depends_on": "ENABLE_MEMORY",
    },
    "NATIVE_MEMORY_IMPORT_TOTAL_CONTENT_MAX_CHARS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "limits",
        "description": "settingDesc.NATIVE_MEMORY_IMPORT_TOTAL_CONTENT_MAX_CHARS",
        "default": 2000000,
        "depends_on": "ENABLE_MEMORY",
        "frontend_visible": False,
    },
    "NATIVE_MEMORY_COMPACTION_CONTENT_MAX_CHARS": {
        "type": SettingType.NUMBER,
        "category": SettingCategory.MEMORY_SEARCH,
        "subcategory": "limits",
        "description": "settingDesc.NATIVE_MEMORY_COMPACTION_CONTENT_MAX_CHARS",
        "default": 4000,
        "depends_on": "ENABLE_MEMORY",
    },
    # ============================================
    # Memory Storage & Policy Settings
    # ============================================,
}
