/** 前端显示名映射（后端只有 slug，显示名在前端维护） */
export const PROVIDER_LABELS: Record<string, string> = {
  openai: "OpenAI",
  anthropic: "Anthropic",
  google: "Google",
  deepseek: "DeepSeek",
  meta: "Meta",
  mistral: "Mistral",
  qwen: "Qwen",
  groq: "Groq",
  xai: "xAI",
  cohere: "Cohere",
  zhipu: "Zhipu",
  moonshot: "Moonshot",
  ollama: "Ollama",
  perplexity: "Perplexity",
  minimax: "MiniMax",
  stepfun: "StepFun",
  doubao: "Doubao",
  spark: "Spark",
  yi: "Yi",
  baichuan: "Baichuan",
  internlm: "InternLM",
  tencent: "Tencent",
  zeroone: "01.AI",
  gemini: "Gemini",
  zai: "ZAI",
  kimi: "Kimi",
  azure: "Azure OpenAI",
  openrouter: "OpenRouter",
  together: "Together AI",
  fireworks: "Fireworks AI",
  deepinfra: "DeepInfra",
  novita: "Novita AI",
  nvidia: "NVIDIA NIM",
  cerebras: "Cerebras",
  sambanova: "SambaNova",
  nebius: "Nebius",
  hyperbolic: "Hyperbolic",
  lambda: "Lambda",
  github: "GitHub Models",
  siliconflow: "SiliconFlow",
  baidu: "Baidu ERNIE",
  modelscope: "ModelScope",
  gitee: "Gitee AI",
};
